receivers:
  otlp:
    protocols:
      grpc:
        endpoint: 0.0.0.0:4317
      http:
        endpoint: 0.0.0.0:4318
  
  # Prometheus receiver to scrape ServiceHost metrics
  prometheus:
    config:
      scrape_configs:
        - job_name: 'portfolio-manager'
          static_configs:
            - targets: ['portfolio_manager:9090']
          scrape_interval: 5s
          metrics_path: /metrics
        - job_name: 'otel-collector'
          static_configs:
            - targets: ['localhost:8888']
          scrape_interval: 5s
          metrics_path: /metrics

processors:
  batch:
  memory_limiter:
    limit_mib: 128
    check_interval: 1s
  
  # Add resource processor to enrich metrics
  resource:
    attributes:
      - key: environment
        value: "development"
        action: upsert
      - key: service.namespace
        value: "seven"
        action: upsert

exporters:
  # OTLP exporter for Jaeger (replaces deprecated jaeger exporter)
  otlp/jaeger:
    endpoint: jaeger:14250
    tls:
      insecure: true
  
  # Debug exporter (replaces deprecated logging exporter)
  debug:
    verbosity: detailed
  
  # Prometheus exporter for metrics
  prometheus:
    endpoint: "0.0.0.0:8888"
    const_labels:
      environment: "development"
      service_namespace: "seven"

service:
  pipelines:
    traces:
      receivers: [otlp]
      processors: [memory_limiter, batch, resource]
      exporters: [otlp/jaeger, debug]
    
    metrics:
      receivers: [otlp, prometheus]
      processors: [memory_limiter, batch, resource]
      exporters: [debug, prometheus]
